#!/bin/bash
PLATFORMIOBIN=/mnt/c/Users/robch/.platformio/penv/Scripts/platformio.exe
#PLATFORMIOBIN=C:/Users/robch/.platformio/penv/Scripts/platformio.exe
BUILDROOT=./.pio/build
OUTROOT=./out/

if [ ! -d $OUTROOT ]; then
    echo $OUTROOT
    mkdir -p $OUTROOT;
else
    rm $OUTROOT/* -f
fi

BINFILE=firmware.bin
RELAYSOURCE=$BUILDROOT/RELAY/$BINFILE
TMP36SOURCE=$BUILDROOT/TMP36/$BINFILE
BMP280SOURCE=$BUILDROOT/BMP280/$BINFILE
DHT11SOURCE=$BUILDROOT/DHT11/$BINFILE
PIRSOURCE=$BUILDROOT/PIR/$BINFILE

RELAYDEST=$OUTROOT/RELAY_$BINFILE
TMP36DEST=$OUTROOT/TMP36_$BINFILE
BMP280DEST=$OUTROOT/BMP280_$BINFILE
DHT11DEST=$OUTROOT/DHT11_$BINFILE
PIRDEST=$OUTROOT/PIR_$BINFILE

echo -e "-----------CLEANING-----------" 
$PLATFORMIOBIN  run --target clean 
echo -e "-----------DONE CLEANING-----------" 
echo -e "-----------BUILDING-----------" 
$PLATFORMIOBIN run
$PLATFORMIOBIN run
echo -e "-----------DONE BUILDING-----------" 
cp $RELAYSOURCE $RELAYDEST
cp $TMP36SOURCE $TMP36DEST 
cp $BMP280SOURCE $BMP280DEST
cp $DHT11SOURCE $DHT11DEST
cp $PIRSOURCE $PIRDEST