name: Main Build
on: push

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: '3.x'
      - name: Install Platform IO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
      - name: Install library dependencies
        run: |
          platformio lib -g install ArduinoLog NTPClient ArduinoJson PubSubClient "Adafruit Unified Sensor" "Adafruit BME280 Library" "DHT sensor library"
      - name: Build
        run: |
          platformio run
          mv .pio/build/RELAY/firmware.bin .pio/build/RELAY/RELAY.bin  
      - uses: actions/upload-artifact@v1
        with:
          name: RELAY
          path: .pio/build/RELAY/RELAY.bin       