name: Main Build
on: push

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: '3.x'
      - name: Install Platform IO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
      - name: Install library dependencies
        run: |
          platformio lib -g install ArduinoLog NTPClient ArduinoJson PubSubClient "Adafruit Unified Sensor" "Adafruit BME280 Library" "DHT sensor library"
      - name: Build
        run: |
          platformio run
      - name: Prepare artifacts
        run: |
          mkdir out
          mv .pio/build/RELAY/firmware.bin out/AthosIoT.RELAY.bin  
          mv .pio/build/TMP36/firmware.bin out/AthosIoT.TMP36.bin  
          mv .pio/build/BMP280/firmware.bin out/AthosIoT.BMP280.bin  
          mv .pio/build/PIR/firmware.bin out/AthosIoT.PIR.bin  
          mv .pio/build/DHT11/firmware.bin out/AthosIoT.DHT11.bin  
          mv .pio/build/ATH_RELAY_MD0/firmware.bin out/AthosIoT.ATH_RELAY_MD0.bin  
      - uses: actions/upload-artifact@v1
        with:
          name: AthosIoT.ATH_RELAY_MD0
          path: out/AthosIoT.ATH_RELAY_MD0.bin      
      - uses: actions/upload-artifact@v1
        with:
          name: AthosIoT.RELAY
          path: out/AthosIoT.RELAY.bin       
      - uses: actions/upload-artifact@v1
        with:
          name: AthosIoT.TMP36
          path: out/AthosIoT.TMP36.bin      
      - uses: actions/upload-artifact@v1
        with:
          name: AthosIoT.BMP280
          path: out/AthosIoT.BMP280.bin       
      - uses: actions/upload-artifact@v1
        with:
          name: AthosIoT.PIR
          path: out/AthosIoT.PIR.bin       
      - uses: actions/upload-artifact@v1
        with:
          name: AthosIoT.DHT11
          path: out/AthosIoT.DHT11.bin       
          