name: Main Build
on: push

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: '3.x'
      - name: Install Platform IO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
      - name: Install library dependencies
        run: |
          platformio lib -g install ArduinoLog NTPClient ArduinoJson PubSubClient DHT
      - name: Build
        run: |
          platformio run