name: Main Build
on: push

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: '3.x'
      - name: Install Platform IO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
      - name: Install library dependencies
        run: |
          platformio lib -g install ArduinoLog NTPClient ArduinoJson PubSubClient "Adafruit Unified Sensor" "Adafruit BME280 Library" "DHT sensor library" "TroykaMQ" 
      - name: Build
        run: |
          platformio run
      - name: Prepare artifacts
        run: |
          mkdir out
          mv .pio/build/RELAY/firmware.bin out/AthosIoT.RELAY.bin  
          mv .pio/build/TMP36/firmware.bin out/AthosIoT.TMP36.bin  
          mv .pio/build/BMP280/firmware.bin out/AthosIoT.BMP280.bin  
          mv .pio/build/PIR/firmware.bin out/AthosIoT.PIR.bin  
          mv .pio/build/DHT11/firmware.bin out/AthosIoT.DHT11.bin  
          mv .pio/build/ATH_RELAY_MD0/firmware.bin out/AthosIoT.ATH_RELAY_MD0.bin  
          mv .pio/build/MOIST_BMP280/firmware.bin out/AthosIoT.MOIST_BMP280_firmware.bin  
          mv .pio/build/MOIST/firmware.bin out/AthosIoT.MOIST_firmware.bin  
          mv .pio/build/MQ2/firmware.bin out/AthosIoT.MQ2_firmware.bin  
          mv .pio/build/RELAY_BMP280/firmware.bin out/AthosIoT.RELAY_BMP280_firmware.bin  
          mv .pio/build/RELAY_PIR/firmware.bin out/AthosIoT.RELAY_PIR_firmware.bin  
          mv .pio/build/RELAY_BMP280_MQ2/firmware.bin out/AthosIoT.RELAY_BMP280_MQ2_firmware.bin  
          mv .pio/build/RELAY_MQ2/firmware.bin out/AthosIoT.RELAY_MQ2_firmware.bin  
          mv .pio/build/STUB/firmware.bin out/AthosIoT.STUB_firmware.bin  
          mv .pio/build/MQ135/firmware.bin out/AthosIoT.MQ135_firmware.bin  
          mv .pio/build/MQ9/firmware.bin out/AthosIoT.MQ9_firmware.bin  
          mv .pio/build/MQ8/firmware.bin out/AthosIoT.MQ8_firmware.bin  
          mv .pio/build/MQ7/firmware.bin out/AthosIoT.MQ7_firmware.bin  
          mv .pio/build/MQ6/firmware.bin out/AthosIoT.MQ6_firmware.bin  
      - uses: actions/upload-artifact@v1
        with:
          name: AthosIoT.MQ7_firmware
          path: out/AthosIoT.MQ7_firmware.bin
      - uses: actions/upload-artifact@v1
        with:
          name: AthosIoT.MQ6_firmware
          path: out/AthosIoT.MQ6_firmware.bin
      - uses: actions/upload-artifact@v1
        with:
          name: AthosIoT.MQ8_firmware
          path: out/AthosIoT.MQ8_firmware.bin
      - uses: actions/upload-artifact@v1
        with:
          name: AthosIoT.MQ9_firmware
          path: out/AthosIoT.MQ9_firmware.bin
      - uses: actions/upload-artifact@v1
        with:
          name: AthosIoT.MQ135_firmware
          path: out/AthosIoT.MQ135_firmware.bin
      - uses: actions/upload-artifact@v1
        with:
          name: AthosIoT.STUB_firmware
          path: out/AthosIoT.STUB_firmware.bin          
      - uses: actions/upload-artifact@v1
        with:
          name: AthosIoT.RELAY_BMP280_MQ2_firmware
          path: out/AthosIoT.RELAY_BMP280_MQ2_firmware.bin
      - uses: actions/upload-artifact@v1
        with:
          name: AthosIoT.RELAY_MQ2_firmware
          path: out/AthosIoT.RELAY_MQ2_firmware.bin
      - uses: actions/upload-artifact@v1
        with:
          name: AthosIoT.RELAY_PIR_firmware
          path: out/AthosIoT.RELAY_PIR_firmware.bin
      - uses: actions/upload-artifact@v1
        with:
          name: AthosIoT.RELAY_BMP280_firmware
          path: out/AthosIoT.RELAY_BMP280_firmware.bin
      - uses: actions/upload-artifact@v1
        with:
          name: AthosIoT.MQ2_firmware
          path: out/AthosIoT.MQ2_firmware.bin      
      - uses: actions/upload-artifact@v1
        with:
          name: AthosIoT.MOIST_firmware
          path: out/AthosIoT.MOIST_firmware.bin      
      - uses: actions/upload-artifact@v1
        with:
          name: AthosIoT.MOIST_BMP280_firmware
          path: out/AthosIoT.MOIST_BMP280_firmware.bin      
      - uses: actions/upload-artifact@v1
        with:
          name: AthosIoT.ATH_RELAY_MD0
          path: out/AthosIoT.ATH_RELAY_MD0.bin      
      - uses: actions/upload-artifact@v1
        with:
          name: AthosIoT.RELAY
          path: out/AthosIoT.RELAY.bin       
      - uses: actions/upload-artifact@v1
        with:
          name: AthosIoT.TMP36
          path: out/AthosIoT.TMP36.bin      
      - uses: actions/upload-artifact@v1
        with:
          name: AthosIoT.BMP280
          path: out/AthosIoT.BMP280.bin       
      - uses: actions/upload-artifact@v1
        with:
          name: AthosIoT.PIR
          path: out/AthosIoT.PIR.bin       
      - uses: actions/upload-artifact@v1
        with:
          name: AthosIoT.DHT11
          path: out/AthosIoT.DHT11.bin       
          